#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <fcntl.h>
#include <sys/time.h>
#include <sys/wait.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stat_arr[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
    char* paren = strchr(line,'(');
    char* left = strrchr(line,'<');
    char* right = strrchr(line,'>');

    if(!paren || !left || !right || left > right){
        printf("parse fall!\n");
        return 1;
    }

    int name_len = paren - line;
    strncpy(syscall_name,line,name_len);
    syscall_name[name_len] = '\0';

    *time = atof(left + 1);
    return 0;
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
    for(int i = 0;i < stats->count;i++){
        if(strcmp(name,stats->stat_arr[i].name) == 0){
            stats->stat_arr[i].time += time;
            stats->total_time += time;
            return;
        }
    }
    syscall_stat newstat;
    strcpy(newstat.name,name);
    newstat.time = time;
    stats->stat_arr[stats->count] = newstat;
    stats->total_time += time;
    stats->count ++;
    return;
}

// 比较函数：按系统调用时间降序排列
int compare_syscalls(const void *a, const void *b) {
    syscall_stat *s1 = (syscall_stat *)a;
    syscall_stat *s2 = (syscall_stat *)b;
    
    if (s2->time > s1->time) return 1;
    if (s2->time < s1->time) return -1;
    return 0;
}

void print_top_syscalls(syscall_stats *stats, int n) {
    if (stats->count == 0) return;

    // 1. 排序：只对已经记录的 count 个系统调用进行排序
    qsort(stats->stat_arr, stats->count, sizeof(syscall_stat), compare_syscalls);

    // 2. 打印前 n 个（如果不足 n 个则打印全部）
    int limit = (stats->count < n) ? stats->count : n;
    for (int i = 0; i < limit; i++) {
        // 计算比例：当前时间 / 总时间 * 100
        // 建议转为 int，符合实验 printf("%d%%") 的要求
        int ratio = (int)(stats->stat_arr[i].time / stats->total_time * 100);
        printf("%s (%d%%)\n", stats->stat_arr[i].name, ratio);
    }

    // 3. 打印 80 个 \0 分隔符 (OJ 判题关键)
    for (int i = 0; i < 80; i++) {
        putchar('\0');
    }
    
    // 4. 强制刷新缓冲区，确保 OJ 能实时看到输出
    fflush(stdout);
}

int main(int argc, char *argv[], char *envp[]) {
    syscall_stats stats;
    int pipefd[2];
    if(pipe(pipefd) == -1){
        printf("pipe fail!\n");
        return 1;
    }
    pid_t pid = fork();
    if(pid == -1){printf("fork fail!\n");return 1;}
    if(pid == 0){
        close(pipefd[0]);
        dup2(pipefd[1],STDERR_FILENO);

        int fd_null = open("/dev/null", O_WRONLY);
        dup2(fd_null, STDOUT_FILENO);

        char** exec_argv = malloc(sizeof(char *) * (argc + 2));
        exec_argv[0] = "strace";
        exec_argv[1] = "-T";
        for(int i = 1;i < argc;i++){
            exec_argv[i + 1] = argv[i];
        }
        exec_argv[argc + 1] = NULL;

        char *path = getenv("PATH");
        if(path){
            char *path_copy = strdup(path);
            char *dir = strtok(path_copy,":");
            while(dir){
                char full_path[1024];
                snprintf(full_path,sizeof(full_path),"%s/strace",dir);
                execve(full_path,exec_argv,envp);
                dir = strtok(NULL,":");
            }
            free(path_copy);
        }
        execve("/usr/bin/strace", exec_argv, envp);
        execve("/bin/strace", exec_argv, envp);
        printf("execve fail\n");
        return 1;
    }else{
        close(pipefd[1]);

        FILE* fp = fdopen(pipefd[0], "r");
        char buf[4096];
        struct timeval last_print, now;
        gettimeofday(&last_print, NULL);

        while(fgets(buf,sizeof(buf),fp)){
            char name[64];
            double t;
            if(!parse_strace_line(buf,name,&t)){
                add_syscall(&stats,name,t);
            }
            gettimeofday(&now, NULL);
            double elapsed = (now.tv_sec - last_print.tv_sec) + 
                             (now.tv_usec - last_print.tv_usec) / 1000000.0;
            
            if (elapsed > 0.1) {
                print_top_syscalls(&stats, 5);
                last_print = now;
            }
        }
        print_top_syscalls(&stats,5);
        wait(NULL);
    }
    return 0;
}
